import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/")
public class HelloServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request,
                         HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html");

        PrintWriter out = response.getWriter();

        out.println("<!DOCTYPE html>");
        out.println("<html>");
        out.println("<head>");
        out.println("<title>My Java Website</title>");
        out.println("<style>");
        out.println("body { font-family: Arial; text-align: center; margin-top: 100px; }");
        out.println("h1 { color: #2c3e50; }");
        out.println("</style>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Welcome to My Java Website!</h1>");
        out.println("<p>This page is generated by a Java Servlet.</p>");
        out.println("</body>");
        out.println("</html>");
    }
}
lkhdygfhglhjkbhb -additional line added by Kranthi